FROM nvidia/cuda:11.2.2-devel-ubuntu20.04

WORKDIR /app/
RUN gpg --keyserver keyserver.ubuntu.com --recv-keys F60F4B3D7FA2AF80
# RUN rm /etc/apt/sources.list.d/cuda.list
# # RUN apt-key adv --fetch-keys
RUN apt update
# RUN apt install python3
# RUN pip3 install -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com
#编译Nginx
# RUN apt install git
# RUN apt install openssl libssl-dev libpcre3 libpcre3-dev zlib1g-dev
# RUN apt install build-essential
# RUN git clone https://github.com/winshining/nginx-http-flv-module.git
# RUN wget http://nginx.org/download/nginx-1.17.9.tar.gz
# RUN tar -zxvf nginx-1.17.9.tar.gz

